//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class UsersAPI {

    /**
     Clear current user's data
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func clearCurrentUserData(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await clearCurrentUserDataWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Clear current user's data
     - DELETE /v1/users/me/data
     - Permanently deletes every category and transaction owned by the authenticated user, while leaving the account itself intact. Preferences and per-client settings are preserved; the identity provider is not contacted and the bearer token remains valid.  Intended for \"start over\" flows where the user wants to wipe their financial history without losing their sign-in or app configuration. The operation is idempotent — a second call on an already-empty account returns 204. 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func clearCurrentUserDataWithRequestBuilder(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v1/users/me/data"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete current user account
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteCurrentUser(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteCurrentUserWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete current user account
     - DELETE /v1/users/me
     - Permanently deletes the authenticated user's account. The API first asks the configured identity provider to delete the user; on success it then removes the local user row, which cascade-deletes all owned data (categories, transactions, preferences, per-client settings).  If the identity provider call fails, no local data is deleted and the request errors so the client can prompt the user to retry. After a successful delete the bearer token may still be valid until it expires; clients should clear local credentials and end the session. 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCurrentUserWithRequestBuilder(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/v1/users/me"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete per-client settings
     
     - parameter clientId: (path) Client this settings row belongs to. See the &#x60;ClientId&#x60; schema for the allowed format. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteCurrentUserClientSettings(clientId: String, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteCurrentUserClientSettingsWithRequestBuilder(clientId: clientId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete per-client settings
     - DELETE /v1/users/me/settings/{clientId}
     - Removes the authenticated user's stored settings for a single client.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter clientId: (path) Client this settings row belongs to. See the &#x60;ClientId&#x60; schema for the allowed format. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCurrentUserClientSettingsWithRequestBuilder(clientId: String, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/users/me/settings/{clientId}"
        let clientIdPreEscape = "\(APIHelper.mapValueToPathItem(clientId))"
        let clientIdPostEscape = clientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{clientId}", with: clientIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get current user
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Me
     */
    open class func getCurrentUser(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> Me {
        return try await getCurrentUserWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get current user
     - GET /v1/users/me
     - Returns the authenticated user's local identity record together with their global preferences, in a single response intended as a client bootstrap call.  If the user has not yet customised their preferences, server defaults are returned (preferences rows are created lazily on first write). 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Me> 
     */
    open class func getCurrentUserWithRequestBuilder(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<Me> {
        let localVariablePath = "/v1/users/me"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Me>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get per-client settings
     
     - parameter clientId: (path) Client this settings row belongs to. See the &#x60;ClientId&#x60; schema for the allowed format. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ClientSettings
     */
    open class func getCurrentUserClientSettings(clientId: String, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> ClientSettings {
        return try await getCurrentUserClientSettingsWithRequestBuilder(clientId: clientId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get per-client settings
     - GET /v1/users/me/settings/{clientId}
     - Returns the authenticated user's stored settings for a single client (e.g. `web`, `mobile-ios`, `telegram-bot`). Returns 404 if no settings have been stored for that client. 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter clientId: (path) Client this settings row belongs to. See the &#x60;ClientId&#x60; schema for the allowed format. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ClientSettings> 
     */
    open class func getCurrentUserClientSettingsWithRequestBuilder(clientId: String, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<ClientSettings> {
        var localVariablePath = "/v1/users/me/settings/{clientId}"
        let clientIdPreEscape = "\(APIHelper.mapValueToPathItem(clientId))"
        let clientIdPostEscape = clientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{clientId}", with: clientIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ClientSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get current user's preferences
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserPreferences
     */
    open class func getCurrentUserPreferences(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> UserPreferences {
        return try await getCurrentUserPreferencesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get current user's preferences
     - GET /v1/users/me/preferences
     - Returns the authenticated user's global preferences (language, currency, timezone). If no preferences row exists yet, server defaults are returned. 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserPreferences> 
     */
    open class func getCurrentUserPreferencesWithRequestBuilder(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<UserPreferences> {
        let localVariablePath = "/v1/users/me/preferences"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserPreferences>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List current user's per-client settings
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ClientSettings]
     */
    open class func listCurrentUserClientSettings(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> [ClientSettings] {
        return try await listCurrentUserClientSettingsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List current user's per-client settings
     - GET /v1/users/me/settings
     - Returns every per-client settings row owned by the authenticated user, oldest first. Intended for management UIs where the user reviews which clients have stored customisations. The list is small in practice (one row per active client) so no pagination is provided. 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ClientSettings]> 
     */
    open class func listCurrentUserClientSettingsWithRequestBuilder(apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<[ClientSettings]> {
        let localVariablePath = "/v1/users/me/settings"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ClientSettings]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update current user's preferences
     
     - parameter userPreferencesWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UserPreferences
     */
    open class func updateCurrentUserPreferences(userPreferencesWrite: UserPreferencesWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> UserPreferences {
        return try await updateCurrentUserPreferencesWithRequestBuilder(userPreferencesWrite: userPreferencesWrite, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update current user's preferences
     - PUT /v1/users/me/preferences
     - Fully updates the authenticated user's global preferences. All fields in the body are applied; the preferences row is created on first call. 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter userPreferencesWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UserPreferences> 
     */
    open class func updateCurrentUserPreferencesWithRequestBuilder(userPreferencesWrite: UserPreferencesWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<UserPreferences> {
        let localVariablePath = "/v1/users/me/preferences"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userPreferencesWrite, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserPreferences>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Upsert per-client settings
     
     - parameter clientId: (path) Client this settings row belongs to. See the &#x60;ClientId&#x60; schema for the allowed format. 
     - parameter clientSettingsWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ClientSettings
     */
    open class func upsertCurrentUserClientSettings(clientId: String, clientSettingsWrite: ClientSettingsWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) async throws(ErrorResponse) -> ClientSettings {
        return try await upsertCurrentUserClientSettingsWithRequestBuilder(clientId: clientId, clientSettingsWrite: clientSettingsWrite, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Upsert per-client settings
     - PUT /v1/users/me/settings/{clientId}
     - Stores (or replaces) the authenticated user's settings for a single client. The body is an opaque JSON object owned by the client app — the server does not validate its shape. 
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter clientId: (path) Client this settings row belongs to. See the &#x60;ClientId&#x60; schema for the allowed format. 
     - parameter clientSettingsWrite: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ClientSettings> 
     */
    open class func upsertCurrentUserClientSettingsWithRequestBuilder(clientId: String, clientSettingsWrite: ClientSettingsWrite, apiConfiguration: BudgetBuddyContractsAPIConfiguration = BudgetBuddyContractsAPIConfiguration.shared) -> RequestBuilder<ClientSettings> {
        var localVariablePath = "/v1/users/me/settings/{clientId}"
        let clientIdPreEscape = "\(APIHelper.mapValueToPathItem(clientId))"
        let clientIdPostEscape = clientIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{clientId}", with: clientIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clientSettingsWrite, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ClientSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
