//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Category: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    public static let monthlyBudgetRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Unique identifier for the category. */
    public var id: UUID
    /** Human-readable name of the category (1–255 characters). */
    public var name: String
    /** Monthly spending budget for this category, in minor units (e.g. 50000 = €500.00). Null when no budget is set. */
    public var monthlyBudget: Int64?

    public init(id: UUID, name: String, monthlyBudget: Int64?) {
        self.id = id
        self.name = name
        self.monthlyBudget = monthlyBudget
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case monthlyBudget
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(monthlyBudget, forKey: .monthlyBudget)
    }
}


extension Category: Identifiable {}
