//
// ClientSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-client UI/UX settings (themes, font sizes, layout preferences, etc.) for a single client of the authenticated user. The &#x60;settings&#x60; payload is opaque to the server — clients own its schema.  */
public struct ClientSettings: Sendable, Codable, Hashable {

    public static let clientIdRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[a-z0-9-]{1,32}$/")
    /** The client this settings row belongs to (matches the path parameter). */
    public var clientId: String
    /** Free-form JSON object owned by the client. The server stores and returns it as-is and does not validate its shape. */
    public var settings: [String: JSONValue]
    /** ISO 8601 timestamp when this client settings row was first created. */
    public var createdAt: Date?
    /** ISO 8601 timestamp when this client settings row was last updated. */
    public var updatedAt: Date?

    public init(clientId: String, settings: [String: JSONValue], createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.clientId = clientId
        self.settings = settings
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId
        case settings
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(settings, forKey: .settings)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

