//
// ClientSettingsWrite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Upsert body — fully replaces any existing settings for the client. */
public struct ClientSettingsWrite: Sendable, Codable, Hashable {

    /** The settings payload to store. */
    public var settings: [String: JSONValue]

    public init(settings: [String: JSONValue]) {
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(settings, forKey: .settings)
    }
}

