//
// ClientSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-client UI/UX settings (themes, font sizes, layout preferences, etc.) for a single client of the authenticated user.  */
public struct ClientSettings: Sendable, Codable, Hashable {

    public static let clientIdRule = StringRule(minLength: nil, maxLength: nil, pattern: "^[a-z0-9-]{1,32}$")
    /** The client this settings row belongs to (matches the path parameter). */
    public var clientId: String
    /** The stored settings payload. */
    public var settings: [String: JSONValue]

    public init(clientId: String, settings: [String: JSONValue]) {
        self.clientId = clientId
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(settings, forKey: .settings)
    }
}

