//
// Me.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Authenticated user&#39;s local identity record together with their global preferences. Intended as a single bootstrap call for client apps.  */
public struct Me: Sendable, Codable, Hashable {

    /** Stable identifier for the authenticated user. Used as the owner of all user-scoped resources and unchanged across sessions. */
    public var id: UUID
    /** The user's current global preferences (server defaults if none have been stored). */
    public var preferences: UserPreferences

    public init(id: UUID, preferences: UserPreferences) {
        self.id = id
        self.preferences = preferences
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case preferences
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(preferences, forKey: .preferences)
    }
}


extension Me: Identifiable {}
